packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.32.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  vitest: ^3.2.4
  zod: ^3.25.76
  "@tanstack/react-query": ^5.84.2
  "@trpc/client": ^11.4.4
  "@trpc/tanstack-react-query": ^11.4.4
  "@trpc/server": ^11.4.4
  "@testing-library/jest-dom": ^6.6.4
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@vitejs/plugin-react": ^4.7.0
  jsdom: ^26.1.0
catalogs:
  react19:
    react: 19.1.1
    react-dom: 19.1.1
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
  tailwindcss:
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.6
    postcss: ^8.5.6
    "@tailwindcss/postcss": ^4.1.11
  supabase:
    "@supabase/supabase-js": ^2.53.0
    "@supabase/ssr": ^0.6.1
onlyBuiltDependencies:
  - esbuild
