packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.32.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  vitest: ^2.1.8
  zod: ^3.25.49
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.0
  "@trpc/tanstack-react-query": ^11.4.0
  "@trpc/server": ^11.4.0
  "@testing-library/jest-dom": ^6.6.4
  "@testing-library/react": ^16.1.0
  "@testing-library/user-event": ^14.5.2
  "@vitejs/plugin-react": ^4.3.4
  jsdom: ^25.0.1
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
onlyBuiltDependencies:
  - esbuild
